version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
    ports:
      - "5432:5432"
    networks:
      - spring-net

  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
    networks:
      - spring-net

networks:
  spring-net:
