spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/testdb}
    username: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:testpass}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  profiles:
    active: local

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

digikat:
  base-url: https://digikat.pl


storage:
  local:
    root: "/movies"